import express from 'express';
import multer from 'multer';
import path from 'node:path';
import { readFile } from 'node:fs/promises';
import { openDatabase, fail, id, now, insert, update, transaction, recordActivity } from './database.mjs';
import { configuration } from './config.mjs';
import { seed } from './seed.mjs';
import { addStudentArt } from './student-art.mjs';
import { auth } from './auth.mjs';
import { createStorage, prepareImage, storeImage } from './storage.mjs';
import { contentSnapshot, saveEvent, saveDocument, mediaDTO, mediaExists, mediaCategories, usages, mediaPublic, text } from './content.mjs';
import { eventPage } from './event-page.mjs';
const noCache = (req, res, next) => { res.set('Cache-Control', 'no-store'); next(); };
export async function createApplication(overrides = {}) {
  const config = configuration(overrides), db = openDatabase(config.dbPath), storage = createStorage(config);
  await seed(db, config.root);
  await addStudentArt(db, config.root);
  const app = express(), security = auth(db, config);
  app.disable('x-powered-by');
  if (process.env.TRUST_PROXY === '1') app.set('trust proxy', 1);
  app.use((req, res, next) => {
    res.set({ 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'same-origin', 'Content-Security-Policy': "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' blob: data:; connect-src 'self'; frame-ancestors 'self'; base-uri 'self'; form-action 'self'; object-src 'none'" });
    if (config.production) res.set('Strict-Transport-Security', 'max-age=31536000'); next();
  });
  app.use(express.json({ limit: '256kb' })); app.use(security.session); app.use('/api', noCache);
  app.get('/api/admin/session', (req, res) => { if (!req.adminSession) return res.status(401).json({ message: 'Please sign in.' }); res.json({ username: req.adminSession.username, csrf: req.adminSession.csrf }); });
  app.post('/api/admin/login', security.origin, security.login);
  app.use('/api/admin', security.requireAdmin, security.origin, security.csrf);
  app.post('/api/admin/logout', security.logout);
  app.get('/api/admin/overview', (req, res) => { const events = db.prepare('SELECT status,published FROM events').all(); res.json({ upcoming: events.filter(e => e.status === 'UPCOMING' && e.published).length, published: events.filter(e => e.published && e.status !== 'ARCHIVED').length, drafts: events.filter(e => !e.published && e.status !== 'ARCHIVED').length, gallery: db.prepare('SELECT count(*) AS n FROM gallery_items').get().n, activity: db.prepare('SELECT action,created_at FROM activity ORDER BY id DESC LIMIT 12').all() }); });
  app.get('/api/admin/events', (req, res) => res.json(db.prepare('SELECT * FROM events ORDER BY created_at DESC').all().map(row => ({ ...row, categories: JSON.parse(row.categories), published: !!row.published, featured: !!row.featured }))));
  const audit = (req, action) => recordActivity(db, req.adminSession.admin_id, action);
  app.post('/api/admin/events', (req, res) => { const eventId = saveEvent(db, req.body); audit(req, `Created event: ${req.body.title}`); res.status(201).json({ id: eventId, message: 'Event saved.' }); });
  app.put('/api/admin/events/:id', (req, res) => { const eventId = saveEvent(db, req.body, req.params.id); audit(req, `${req.body.published ? 'Published' : 'Saved'} event: ${req.body.title}`); res.json({ id: eventId, message: req.body.published ? 'Event published successfully.' : 'Changes saved as draft.' }); });
  app.delete('/api/admin/events/:id', (req, res) => { const event = db.prepare('SELECT * FROM events WHERE id=?').get(req.params.id); if (!event) throw fail(404, 'Event not found.'); update(db, 'events', { status: 'ARCHIVED', published: 0, updated_at: now() }, 'id', event.id); audit(req, `Archived event: ${event.title}`); res.json({ message: 'Event archived. Its photos are retained and its associated gallery is hidden.' }); });
  app.get('/api/admin/documents/:name', (req, res) => { const row = db.prepare('SELECT * FROM documents WHERE name=?').get(req.params.name); if (!row) throw fail(404, 'Content section not found.'); res.json({ ...row, draft: JSON.parse(row.draft), published: JSON.parse(row.published) }); });
  app.put('/api/admin/documents/:name', (req, res) => { const result = saveDocument(db, req.params.name, req.body.data, req.body.publish === true); audit(req, `${req.body.publish ? 'Published' : 'Saved draft'}: ${req.params.name}`); res.json({ data: result, message: req.body.publish ? 'Changes published.' : 'Changes saved as draft. Preview before publishing.' }); });
  app.get('/api/admin/media', (req, res) => res.json(db.prepare('SELECT * FROM media WHERE deleted_at IS NULL ORDER BY created_at DESC').all().map(row => ({ ...mediaDTO(row), used_in: usages(db, row.id) }))));
  const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024, files: 1, fields: 8, fieldSize: 10000, parts: 10 }, fileFilter: (req, file, cb) => cb(['image/jpeg','image/png','image/webp','image/avif'].includes(file.mimetype) ? null : fail(400, 'Use a JPG, PNG, WebP or AVIF image.'), true) });
  let uploads = 0;
  const uploadLimit = (req, res, next) => { if (uploads >= 2) return next(fail(429, 'Other photos are uploading. Try again shortly.')); uploads++; let released = false; const release = () => { if (!released) { released = true; uploads--; } }; res.on('finish', release); res.on('close', release); next(); };
  async function uploadPhoto(req, res) {
    if (!req.file) throw fail(400, 'Choose a photo to upload.');
    const existing = req.params.id && db.prepare('SELECT * FROM media WHERE id=? AND deleted_at IS NULL').get(req.params.id);
    if (req.params.id && !existing) throw fail(404, 'Photo not found.');
    const category = req.body.category || existing?.category || 'GENERAL'; if (!mediaCategories.includes(category)) throw fail(400, 'Choose a valid photo category.');
    const alt = text(req.body.alt_text || existing?.alt_text || '', 500, true);
    const saved = await storeImage(storage, await prepareImage(req.file.buffer));
    const mediaId = existing?.id || id();
    const record = { ...saved, filename: path.basename(req.file.originalname).slice(0, 180), alt_text: alt, category, updated_at: now() };
    if (existing) update(db, 'media', record, 'id', mediaId); else insert(db, 'media', { id: mediaId, ...record, created_at: now(), deleted_at: null });
    audit(req, `${existing ? 'Replaced' : 'Uploaded'} photo: ${record.filename}`);
    res.status(existing ? 200 : 201).json({ ...mediaDTO(db.prepare('SELECT * FROM media WHERE id=?').get(mediaId)), message: existing ? 'Photo replaced in every connected placement.' : 'Photo uploaded.' });
  }
  app.post('/api/admin/media', uploadLimit, upload.single('file'), uploadPhoto);
  app.post('/api/admin/media/:id/replace', uploadLimit, upload.single('file'), uploadPhoto);
  app.put('/api/admin/media/:id', (req, res) => { mediaExists(db, req.params.id, true); if (!mediaCategories.includes(req.body.category)) throw fail(400, 'Choose a valid photo category.'); update(db, 'media', { alt_text: text(req.body.alt_text, 500, true), category: req.body.category, updated_at: now() }, 'id', req.params.id); audit(req, 'Updated photo details'); res.json({ message: 'Photo details saved.' }); });
  app.delete('/api/admin/media/:id', (req, res) => { mediaExists(db, req.params.id, true); const references = usages(db, req.params.id); if (references.length) return res.status(409).json({ message: 'This photo is still in use. Remove or replace these placements first.', used_in: references }); update(db, 'media', { deleted_at: now(), updated_at: now() }, 'id', req.params.id); audit(req, 'Removed unused photo from library'); res.json({ message: 'Photo removed from the library. Stored files are retained for recovery.' }); });
  app.get('/api/admin/gallery', (req, res) => res.json(db.prepare('SELECT * FROM gallery_items ORDER BY position,created_at,id').all()));
  function galleryData(body) { mediaExists(db, body.media_id, true); if (body.event_id && !db.prepare('SELECT id FROM events WHERE id=?').get(body.event_id)) throw fail(400, 'Choose an existing event.'); if (!mediaCategories.includes(body.category)) throw fail(400, 'Choose a valid category.'); return { media_id: body.media_id, event_id: body.event_id || null, title: text(body.title, 180, true), caption: text(body.caption || '', 1000), category: body.category, wide: body.wide ? 1 : 0, featured: body.featured ? 1 : 0, published: body.published ? 1 : 0, updated_at: now() }; }
  app.post('/api/admin/gallery', (req, res) => { const record = galleryData(req.body), galleryId = id(); insert(db, 'gallery_items', { id: galleryId, ...record, position: db.prepare('SELECT coalesce(max(position),-1)+1 AS n FROM gallery_items').get().n, focal_position: 'center', created_at: now() }); audit(req, `Added gallery photo: ${record.title}`); res.status(201).json({ id: galleryId, message: 'Photo added to gallery.' }); });
  app.put('/api/admin/gallery/reorder', (req, res) => { const ids = req.body.ids, actual = db.prepare('SELECT id FROM gallery_items').all().map(row => row.id); if (!Array.isArray(ids) || ids.length !== actual.length || new Set(ids).size !== actual.length || ids.some(value => !actual.includes(value))) throw fail(409, 'The gallery changed. Refresh before reordering.'); transaction(db, () => ids.forEach((value, i) => db.prepare('UPDATE gallery_items SET position=?,updated_at=? WHERE id=?').run(i, now(), value))); audit(req, 'Reordered gallery'); res.json({ message: 'Gallery order saved.' }); });
  app.put('/api/admin/gallery/:id', (req, res) => { if (!db.prepare('SELECT id FROM gallery_items WHERE id=?').get(req.params.id)) throw fail(404, 'Gallery photo not found.'); update(db, 'gallery_items', galleryData(req.body), 'id', req.params.id); audit(req, 'Updated gallery photo'); res.json({ message: 'Gallery changes saved.' }); });
  app.delete('/api/admin/gallery/:id', (req, res) => { db.prepare('DELETE FROM gallery_items WHERE id=?').run(req.params.id); audit(req, 'Removed photo from gallery (media retained)'); res.json({ message: 'Removed from gallery. The photo remains in your media library.' }); });
  app.get('/api/content', (req, res) => res.json(contentSnapshot(db)));
  for (const [route, property] of [['events','events'],['gallery','gallery'],['homepage','homepage'],['art-forms','artForms'],['team','team']]) app.get(`/api/${route}`, (req, res) => res.json(contentSnapshot(db)[property]));
  app.get('/api/events/:slug', (req, res) => { const event = contentSnapshot(db).events.find(e => e.slug === req.params.slug); if (!event) throw fail(404, 'Event not found.'); res.json(event); });
  app.get('/content-data.js', noCache, (req, res) => { const preview = req.query.preview === '1'; if (preview && !req.adminSession) throw fail(401, 'Sign in to preview drafts.'); res.type('js').send(`window.VPA_CONTENT=${JSON.stringify(contentSnapshot(db, preview)).replaceAll('<', '\\u003c').replaceAll('\u2028','\\u2028').replaceAll('\u2029','\\u2029')};`); });
  app.get('/media/:id', async (req, res) => { const row = db.prepare('SELECT * FROM media WHERE id=? AND deleted_at IS NULL').get(req.params.id); if (!row || (!req.adminSession && !mediaPublic(db, row.id))) throw fail(404, 'Photo not found.'); res.set('Cache-Control', 'private, no-cache'); res.type(row.mime_type); if (row.source === 'asset') return res.send(await readFile(path.join(config.root, 'assets', row.storage_key))); const variants = JSON.parse(row.variants); res.send(await storage.get(req.query.size === 'small' && variants.small ? variants.small : row.storage_key)); });
  const template = await readFile(path.join(config.root, 'index.html'), 'utf8');
  app.get('/', noCache, (req, res) => res.type('html').send(template));
  app.get('/events/:slug', noCache, (req, res) => { const snapshot = contentSnapshot(db), event = snapshot.events.find(e => e.slug === req.params.slug); if (!event) return res.status(404).type('html').send('<h1>Event not found</h1><a href="/">Return to VPA</a>'); res.type('html').send(eventPage(template, event, snapshot.gallery, false)); });
  app.get('/admin/login', noCache, (req, res) => req.adminSession ? res.redirect('/admin') : res.sendFile(path.join(config.root, 'admin/login.html')));
  app.use('/admin', noCache, (req, res, next) => { res.set('X-Robots-Tag', 'noindex, nofollow'); if (!req.adminSession) return res.redirect('/admin/login'); next(); });
  app.get('/admin/preview', (req, res) => res.type('html').send(template.replace('src="/content-data.js"', 'src="/content-data.js?preview=1"').replace('<body>', '<body><div class="preview-banner">PRIVATE PREVIEW · Includes saved drafts <a href="/admin">Return to Control Room</a></div>')));
  app.get('/admin/preview/events/:id', (req, res) => { const snapshot = contentSnapshot(db, true), event = snapshot.events.find(e => e.id === req.params.id); if (!event) throw fail(404, 'Event not found.'); res.type('html').send(eventPage(template, event, snapshot.gallery, true)); });
  app.get(['/admin','/admin/events','/admin/gallery','/admin/media','/admin/homepage','/admin/art-forms','/admin/content','/admin/team'], (req, res) => res.sendFile(path.join(config.root, 'admin/index.html')));
  app.get('/admin-assets/:file', (req, res) => { if (!['admin.js','admin.css','login.js'].includes(req.params.file)) throw fail(404, 'Page not found.'); res.sendFile(path.join(config.root, 'admin', req.params.file)); });
  app.use('/assets', express.static(path.join(config.root, 'assets'), { index: false, dotfiles: 'deny' }));
  for (const file of ['styles.css','experience.css','experience.js','app.js','event-page.js']) app.get(`/${file}`, (req, res) => res.sendFile(path.join(config.root, file)));
  app.get('/favicon.ico', (req, res) => res.status(204).end());
  app.use((req, res) => res.status(404).json({ message: 'Page not found.' }));
  app.use((error, req, res, next) => { if (res.headersSent) return next(error); const status = error.code?.startsWith('LIMIT_') ? 400 : error.status || 500; if (status >= 500) console.error('Request failed:', error.message); res.status(status).json({ message: status >= 500 ? 'Something went wrong while saving or loading. Please try again.' : error.code?.startsWith('LIMIT_') ? 'Upload one image at a time, no larger than 10 MB.' : error.message }); });
  return { app, db, config, storage };
}
