const page = document.querySelector('#page'), feedback = document.querySelector('#feedback');
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' })[c]);
const categories = ['MUSIC','DANCE','FINE ARTS','GENERAL'], photoCategories = [...categories,'EVENTS','TEAM'];
let csrf = '', dirty = false, busy = false, media = [], events = [], gallery = [];
const notice = (message, error = false) => { feedback.textContent = message; feedback.classList.toggle('error', error); };
async function api(url, options = {}) {
  const response = await fetch(url, { ...options, headers: { ...(options.body instanceof FormData ? {} : { 'Content-Type':'application/json' }), 'X-CSRF-Token':csrf, ...options.headers } });
  const data = await response.json();
  if (response.status === 401) { notice('Your session expired. Your editor is still here. Sign in in another tab, then retry saving.', true); if (!document.querySelector('#sign-in-again')) { const link = document.createElement('a'); link.id = 'sign-in-again'; link.href = '/admin/login'; link.target = '_blank'; link.textContent = ' Sign in again ↗'; feedback.append(link); } throw new Error(data.message); }
  if (!response.ok) throw new Error(data.message + (data.used_in?.length ? ` Used in: ${data.used_in.join(', ')}` : ''));
  return data;
}
async function refreshSession() { const session = await api('/api/admin/session'); csrf = session.csrf; document.querySelector('#signed-in').textContent = `Signed in as ${session.username}`; }
async function operation(work, message = 'Saving…') {
  if (busy) return; busy = true; const buttons = [...document.querySelectorAll('#page button')]; buttons.forEach(button => button.disabled = true); notice(message);
  try { await refreshSession(); await work(); } catch (error) { notice(error.message || 'Could not connect. Please try again.',true); }
  finally { busy = false; buttons.filter(button => button.isConnected).forEach(button => button.disabled = false); }
}
const json = data => JSON.stringify(data);
const field = (label,name,value='',type='text',extra='') => `<label>${escape(label)}<input name="${name}" type="${type}" value="${escape(value)}" ${extra}></label>`;
const area = (label,name,value='',max=3000) => `<label>${escape(label)}<textarea name="${name}" maxlength="${max}">${escape(value)}</textarea></label>`;
const check = (label,name,value=false) => `<label><input type="checkbox" name="${name}" ${value ? 'checked' : ''}>${escape(label)}</label>`;
const options = (values,selected) => values.map(value => `<option value="${escape(value)}" ${value===selected?'selected':''}>${escape(value)}</option>`).join('');
const select = (label,name,values,selected) => `<label>${escape(label)}<select name="${name}">${options(values,selected)}</select></label>`;
function photoSelect(label,name,selected,required=false) { const photo = media.find(item => item.id===selected); return `<label>${escape(label)}<select name="${name}" data-photo-select ${required?'required':''}><option value="">${required?'Choose a photo':'No photo selected'}</option>${media.map(item=>`<option value="${item.id}" ${item.id===selected?'selected':''}>${escape(item.filename)}</option>`).join('')}</select><img class="photo-preview" src="${photo?escape(photo.url):''}" alt="Selected photo preview" ${photo?'':'hidden'}></label>`; }
const eventSelect = (name,selected) => `<label>Associated event<select name="${name}"><option value="">No event</option>${events.map(event=>`<option value="${event.id}" ${event.id===selected?'selected':''}>${escape(event.title)}</option>`).join('')}</select></label>`;
function heading(title,subtitle='',actions='') { return `<div class="page-head"><div><p class="eyebrow">VPA CONTROL ROOM</p><h1>${escape(title)}</h1><p class="muted">${escape(subtitle)}</p></div><div class="actions">${actions}</div></div>`; }
function editorActions(preview='/admin/preview') { return `<div class="actions editor-actions"><button type="submit" name="action" value="draft">Save draft</button><button type="submit" name="action" value="publish">Publish changes</button><a class="action secondary" href="${preview}" target="_blank" rel="noopener" data-preview>Preview saved changes ↗</a></div>`; }
async function loadLibrary() { [media,events] = await Promise.all([api('/api/admin/media'),api('/api/admin/events')]); }
function canLeave() { return !busy && (!dirty || confirm('You have unsaved changes. Leave without saving?')); }
async function navigate(url,replace=false) { if (!canLeave()) return; dirty=false; if (replace) history.replaceState({},'',url); else history.pushState({},'',url); await render(); }
document.addEventListener('click', event=>{ const link=event.target.closest('a[data-route]'); if(link){event.preventDefault();navigate(link.href);} const preview=event.target.closest('[data-preview]');if(preview&&dirty){event.preventDefault();notice('Save your draft before previewing these changes.',true);} });
document.addEventListener('input',event=>{if(event.target.closest('[data-editor]'))dirty=true;});
document.addEventListener('change',event=>{if(event.target.matches('[data-photo-select]')){const photo=media.find(item=>item.id===event.target.value);const image=event.target.parentElement.querySelector('img');image.hidden=!photo;if(photo)image.src=photo.url;}});
window.addEventListener('beforeunload',event=>{if(dirty||busy){event.preventDefault();event.returnValue='';}});
let previousURL=location.href;
window.addEventListener('popstate',()=>{if(!canLeave()){history.pushState({},'',previousURL);return;}dirty=false;render();});
document.querySelector('#logout').addEventListener('click',()=>{if(!canLeave())return;operation(async()=>{await api('/api/admin/logout',{method:'POST'});dirty=false;location.replace('/admin/login');},'Signing out…');});
async function dashboard(){ const data=await api('/api/admin/overview');page.innerHTML=heading('Your creative world.','Keep the next performance, photo and announcement moving.')+`<div class="stats">${[['Upcoming events',data.upcoming],['Published events',data.published],['Gallery photos',data.gallery],['Event drafts',data.drafts]].map(([label,value])=>`<div class="stat"><strong>${value}</strong><span>${label}</span></div>`).join('')}</div><section class="panel"><h2>Make something happen.</h2><div class="actions"><a class="action" data-route href="/admin/events?edit=new">+ Add event</a><a class="action secondary" data-route href="/admin/gallery?upload=1">+ Add photos</a><a class="action secondary" data-route href="/admin/homepage">Edit homepage</a></div></section><section class="panel"><h2>Recent activity</h2>${data.activity.length?`<ul class="activity">${data.activity.map(item=>`<li>${escape(item.action)}<time>${escape(new Date(item.created_at).toLocaleString())}</time></li>`).join('')}</ul>`:'<p class="muted">Your publishing and editing activity will appear here.</p>'}</section>`; }
async function eventList(){
  await loadLibrary();const edit=new URLSearchParams(location.search).get('edit');if(edit)return eventEditor(edit);
  page.innerHTML=heading('Events','Draft it. Preview it. Give it a stage.','<a class="action" data-route href="/admin/events?edit=new">+ Add event</a>')+`<div class="toolbar">${select('Show','status',['ALL','DRAFT','UPCOMING','COMPLETED','ARCHIVED'],'ALL')}${field('Search events','search')}</div><div class="list" id="event-rows"></div>`;
  const draw=()=>{const status=page.querySelector('[name=status]').value,q=page.querySelector('[name=search]').value.toLowerCase();const rows=events.filter(item=>(status==='ALL'||(status==='DRAFT'?!item.published&&item.status!=='ARCHIVED':item.status===status))&&item.title.toLowerCase().includes(q));document.querySelector('#event-rows').innerHTML=rows.length?rows.map(item=>`<article class="list-row"><div><span class="badge">${item.published?'PUBLISHED':'PRIVATE'} · ${escape(item.status)}</span><h3>${escape(item.title)}</h3><p>${escape(item.date||'Date not supplied')} · ${escape(item.categories.join(' + '))}</p></div><div class="actions"><a class="action secondary" data-route href="/admin/events?edit=${item.id}">Edit</a>${item.status!=='ARCHIVED'?`<a class="action secondary" target="_blank" rel="noopener" href="/admin/preview/events/${item.id}">Preview ↗</a><button class="secondary" data-event-action="${item.published?'unpublish':'publish'}" data-id="${item.id}">${item.published?'Unpublish':'Publish'}</button><button class="secondary" data-event-action="complete" data-id="${item.id}">Mark completed</button><button class="danger" data-event-action="archive" data-id="${item.id}">Archive</button>`:''}</div></article>`).join(''):'<div class="empty">No matching events. Add an event when there is something new to announce.</div>';};draw();page.querySelector('.toolbar').addEventListener('input',draw);
  page.querySelector('#event-rows').addEventListener('click',event=>{const button=event.target.closest('[data-event-action]');if(!button)return;const item=events.find(row=>row.id===button.dataset.id),action=button.dataset.eventAction;if(['archive','unpublish'].includes(action)&&!confirm(action==='archive'?'Archive this event? It and its associated gallery will be hidden. Photos remain in the media library.':'Unpublish this event? Its event page and associated gallery will become private.'))return;operation(async()=>{let result;if(action==='archive')result=await api(`/api/admin/events/${item.id}`,{method:'DELETE'});else result=await api(`/api/admin/events/${item.id}`,{method:'PUT',body:json({...item,published:action==='unpublish'?false:action==='publish'?true:item.published,status:action==='complete'?'COMPLETED':action==='publish'&&item.status==='DRAFT'?'UPCOMING':item.status})});await eventList();notice(result.message);});});
}
function eventEditor(eventId){
  const item=eventId==='new'?{title:'',slug:'',categories:['GENERAL'],status:'DRAFT'}:events.find(row=>row.id===eventId);if(!item){page.innerHTML='<p>Event not found.</p>';return;}
  page.innerHTML=heading(eventId==='new'?'A new event.':'Edit event.', 'Save draft makes this event private. Publish when it is ready.','<a class="action secondary" data-route href="/admin/events">All events</a>')+`<form id="event-editor" data-editor><fieldset><legend>Event details</legend><div class="form-grid">${field('Event name','title',item.title,'text','required maxlength="180"')}${field('Page address (optional; generated if blank)','slug',item.slug,'text','maxlength="100" pattern="[a-z0-9-]+"')}${field('Date','date',item.date,'date')}${field('End date (optional)','end_date',item.end_date,'date')}${field('Time (optional)','time',item.time,'time')}${field('Venue','venue',item.venue)}${field('Type / event label','event_type',item.event_type)}<div><label>Categories</label><div class="checks">${categories.map(category=>check(category,'category',item.categories.includes(category)).replace('name="category"',`name="category" value="${category}"`)).join('')}</div></div><div class="full">${area('Short description','short_description',item.short_description,500)}</div><div class="full">${area('Full description','description',item.description,15000)}</div></div></fieldset><fieldset><legend>Media</legend><p class="hint">Upload new files in the Media library first, then select them here. Save the event before adding its gallery.</p><div class="form-grid">${photoSelect('Event poster','poster_id',item.poster_id)}${photoSelect('Cover photo','cover_id',item.cover_id)}</div>${eventId!=='new'?`<p><a class="inline-link" data-route href="/admin/gallery?event=${eventId}&upload=1">Add or manage this event’s gallery ↗</a></p>`:''}</fieldset><fieldset><legend>Visibility</legend><div class="form-grid">${select('Event status','status',['DRAFT','UPCOMING','COMPLETED','ARCHIVED'],item.status)}${check('Feature this event','featured',item.featured)}</div></fieldset>${editorActions(eventId==='new'?'/admin/preview':`/admin/preview/events/${eventId}`)}</form>`;
  page.querySelector('form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,values=new FormData(form),publish=event.submitter.value==='publish';const body={...Object.fromEntries(values),categories:values.getAll('category'),featured:values.has('featured'),published:publish};if(publish&&body.status==='DRAFT')body.status='UPCOMING';if(publish&&body.status==='ARCHIVED'){notice('Choose Upcoming or Completed before publishing.',true);return;}operation(async()=>{const result=await api(eventId==='new'?'/api/admin/events':`/api/admin/events/${eventId}`,{method:eventId==='new'?'POST':'PUT',body:json(body)});dirty=false;history.replaceState({},'',`/admin/events?edit=${result.id}`);await eventList();notice(publish?'Event published successfully.':'Changes saved as draft. Use Preview saved changes to review.');});});
}
async function mediaPage(){await loadLibrary();const edit=new URLSearchParams(location.search).get('edit');if(edit)return mediaEditor(edit);page.innerHTML=heading('Media library','Replace a photo once. Update every connected placement.','<button id="upload-open">+ Upload photos</button>')+`<div id="upload-area"></div><div class="toolbar">${field('Search photos','search')}${select('Category','category',['ALL',...photoCategories],'ALL')}</div><div class="media-grid" id="media-items"></div>`;document.querySelector('#upload-open').addEventListener('click',()=>uploadForm(false));const draw=()=>{const q=page.querySelector('[name=search]').value.toLowerCase(),category=page.querySelector('[name=category]').value;const rows=media.filter(photo=>(category==='ALL'||photo.category===category)&&`${photo.filename} ${photo.alt_text}`.toLowerCase().includes(q));document.querySelector('#media-items').innerHTML=rows.length?rows.map(photo=>`<article class="media-card"><img src="${escape(photo.url)}" alt="${escape(photo.alt_text)}" loading="lazy"><div class="card-body"><h3>${escape(photo.filename)}</h3><p>${escape(photo.category)} · ${photo.width} × ${photo.height}</p><p>${photo.used_in.length} connected placements</p><a class="action secondary" data-route href="/admin/media?edit=${photo.id}">Edit / replace</a></div></article>`).join(''):'<p class="empty">No matching photos.</p>';};draw();page.querySelector('.toolbar').addEventListener('input',draw);}
function mediaEditor(mediaId){const photo=media.find(item=>item.id===mediaId);if(!photo){page.innerHTML='<p>Photo not found.</p>';return;}page.innerHTML=heading('Photo details',photo.filename,'<a class="action secondary" data-route href="/admin/media">Media library</a>')+`<div class="form-grid"><section class="panel"><img class="photo-preview" src="${escape(photo.url)}" alt="${escape(photo.alt_text)}"><h2>Where it appears</h2>${photo.used_in.length?`<ul>${photo.used_in.map(use=>`<li>${escape(use)}</li>`).join('')}</ul>`:'<p>This photo is not currently connected to content.</p>'}</section><form class="panel" id="media-editor" data-editor>${area('Describe the image (alt text)','alt_text',photo.alt_text,500)}${select('Category','category',photoCategories,photo.category)}<div class="actions"><button>Save photo details</button></div></form></div><form id="replace-photo" class="panel" data-editor><h2>Replace this photo</h2><p class="notice">Replacement updates every placement immediately, including the live website.</p><label>New image<input type="file" name="file" accept="image/jpeg,image/png,image/webp,image/avif" required></label><button>Replace image</button></form><button class="danger" id="delete-photo">Remove from library</button>`;
  document.querySelector('#media-editor').addEventListener('submit',event=>{event.preventDefault();const body=Object.fromEntries(new FormData(event.currentTarget));operation(async()=>{const result=await api(`/api/admin/media/${mediaId}`,{method:'PUT',body:json(body)});dirty=false;notice(result.message);});});
  document.querySelector('#replace-photo').addEventListener('submit',event=>{event.preventDefault();if(!confirm('Replace this photo in every connected placement, including the live website?'))return;const body=new FormData(event.currentTarget);body.set('alt_text',document.querySelector('#media-editor [name=alt_text]').value);body.set('category',document.querySelector('#media-editor [name=category]').value);operation(async()=>{const result=await api(`/api/admin/media/${mediaId}/replace`,{method:'POST',body});dirty=false;await mediaPage();notice(result.message);},'Uploading replacement…');});
  document.querySelector('#delete-photo').addEventListener('click',()=>{if(!confirm('Remove this unused photo from the library? Photos still in use cannot be removed.'))return;operation(async()=>{const result=await api(`/api/admin/media/${mediaId}`,{method:'DELETE'});dirty=false;history.replaceState({},'','/admin/media');await mediaPage();notice(result.message);});});
}
function uploadForm(toGallery){
  const selectedEvent=new URLSearchParams(location.search).get('event')||'';
  document.querySelector('#upload-area').innerHTML=`<form id="upload-form" class="panel" data-editor><h2>${toGallery?'Add photos to the gallery':'Upload photos'}</h2><p class="hint">JPG, PNG, WebP or AVIF · up to 10 MB each. Select multiple files; they upload one at a time.</p><div class="form-grid">${select('Photo category','upload_category',photoCategories,'EVENTS')}${toGallery?eventSelect('upload_event',selectedEvent):''}</div>${toGallery?check('Publish these gallery photos (draft events remain private)','upload_published',false):''}<label>Select images<input type="file" id="upload-files" accept="image/jpeg,image/png,image/webp,image/avif" multiple required></label><div id="upload-descriptions"></div><button>Upload photos</button></form>`;
  const input=document.querySelector('#upload-files');let successful=new Map();
  input.addEventListener('change',()=>{successful=new Map();document.querySelector('#upload-descriptions').innerHTML=[...input.files].map((file,i)=>`<div class="upload-item"><span>${escape(file.name)}</span><label>Describe this photo<input name="alt_${i}" maxlength="500" required></label></div>`).join('');});
  document.querySelector('#upload-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,files=[...input.files];if(!files.length)return;operation(async()=>{let count=0;for(const [i,file] of files.entries()){notice(`Uploading photo ${i+1} of ${files.length}…`);let record=successful.get(i);if(!record){const body=new FormData();body.set('file',file);body.set('alt_text',form.elements[`alt_${i}`].value);body.set('category',form.elements.upload_category.value);record=await api('/api/admin/media',{method:'POST',body});successful.set(i,record);}if(toGallery&&!record.associated){await api('/api/admin/gallery',{method:'POST',body:json({media_id:record.id,event_id:form.elements.upload_event.value,category:form.elements.upload_category.value,title:form.elements[`alt_${i}`].value.slice(0,180),caption:'',published:form.elements.upload_published.checked,wide:record.width>record.height,featured:false})});record.associated=true;}count++;}dirty=false;if(toGallery)await galleryPage();else await mediaPage();notice(`${count} photos uploaded${toGallery?' and added to the gallery':''}.`);},'Preparing upload…');});
}
async function galleryPage(){
  await loadLibrary();gallery=await api('/api/admin/gallery');const query=new URLSearchParams(location.search),edit=query.get('edit');if(edit)return galleryEditor(edit);
  page.innerHTML=heading('The visual diary.','Drag photos to reorder, or use the arrow buttons. Reordering updates the live gallery.','<button id="add-gallery">+ Upload photos</button><button id="choose-gallery" class="secondary">Choose existing photo</button>')+'<div id="upload-area"></div><div class="list" id="gallery-rows"></div>';
  const draw=()=>{document.querySelector('#gallery-rows').innerHTML=gallery.length?gallery.map((item,index)=>{const photo=media.find(row=>row.id===item.media_id);return `<article class="list-row gallery-row" draggable="true" data-id="${item.id}"><div class="gallery-summary">${photo?`<img src="${escape(photo.url)}" alt="${escape(photo.alt_text)}" loading="lazy">`:''}<div><span class="badge">${item.published?'PUBLISHED':'DRAFT'}${item.featured?' · FEATURED':''}</span><h3>${escape(item.title)}</h3><p>${escape(events.find(row=>row.id===item.event_id)?.title||item.category)}</p></div></div><div class="actions"><div class="gallery-order"><button class="secondary" data-move="-1" data-index="${index}" aria-label="Move ${escape(item.title)} up" ${index===0?'disabled':''}>↑</button><button class="secondary" data-move="1" data-index="${index}" aria-label="Move ${escape(item.title)} down" ${index===gallery.length-1?'disabled':''}>↓</button></div><a class="action secondary" data-route href="/admin/gallery?edit=${item.id}">Edit</a><button class="danger" data-remove="${item.id}">Remove</button></div></article>`;}).join(''):'<div class="empty">No gallery photos yet. Upload photos or choose from the media library.</div>';};draw();
  document.querySelector('#add-gallery').addEventListener('click',()=>uploadForm(true));document.querySelector('#choose-gallery').addEventListener('click',()=>navigate('/admin/gallery?edit=new'));if(query.has('upload'))uploadForm(true);
  async function move(from,to){if(from===to||to<0||to>=gallery.length)return;const reordered=[...gallery];reordered.splice(to,0,reordered.splice(from,1)[0]);await operation(async()=>{await api('/api/admin/gallery/reorder',{method:'PUT',body:json({ids:reordered.map(item=>item.id)})});gallery=reordered;draw();notice('Gallery order saved.');});}
  const rows=document.querySelector('#gallery-rows');let dragged;
  rows.addEventListener('dragstart',event=>{const row=event.target.closest('.gallery-row');if(row){dragged=gallery.findIndex(item=>item.id===row.dataset.id);row.classList.add('dragging');event.dataTransfer.setData('text/plain',row.dataset.id);}});
  rows.addEventListener('dragover',event=>event.preventDefault());rows.addEventListener('drop',event=>{event.preventDefault();const row=event.target.closest('.gallery-row');if(row&&dragged!==undefined)move(dragged,gallery.findIndex(item=>item.id===row.dataset.id));});rows.addEventListener('dragend',()=>{rows.querySelectorAll('.dragging').forEach(row=>row.classList.remove('dragging'));dragged=undefined;});
  rows.addEventListener('click',event=>{const moveButton=event.target.closest('[data-move]');if(moveButton)move(Number(moveButton.dataset.index),Number(moveButton.dataset.index)+Number(moveButton.dataset.move));const remove=event.target.closest('[data-remove]');if(remove&&confirm('Remove this photo from the gallery? The original stays in the media library.'))operation(async()=>{const result=await api(`/api/admin/gallery/${remove.dataset.remove}`,{method:'DELETE'});await galleryPage();notice(result.message);});});
}
function galleryEditor(itemId){const item=itemId==='new'?{category:'EVENTS'}:gallery.find(row=>row.id===itemId);if(!item){page.innerHTML='<p>Gallery photo not found.</p>';return;}const photo=media.find(row=>row.id===item.media_id);page.innerHTML=heading('Gallery photo','Published photo edits take effect immediately. Save as draft to keep a photo private.','<a class="action secondary" data-route href="/admin/gallery">All photos</a>')+`<form id="gallery-editor" data-editor><div class="panel form-grid">${photoSelect('Photo','media_id',item.media_id,true)}${eventSelect('event_id',item.event_id)}${field('Title','title',item.title,'text','required maxlength="180"')}${select('Category','category',photoCategories,item.category)}${area('Caption','caption',item.caption,1000)}${area('Describe image (alt text; updates all placements)','alt_text',photo?.alt_text||'',500)}<div class="checks full">${check('Feature on homepage','featured',item.featured)}${check('Wide composition','wide',item.wide)}</div></div>${editorActions()}</form>`;
  const form=document.querySelector('#gallery-editor');form.elements.media_id.addEventListener('change',()=>{form.elements.alt_text.value=media.find(row=>row.id===form.elements.media_id.value)?.alt_text||'';});
  form.addEventListener('submit',event=>{event.preventDefault();const values=new FormData(form),body={...Object.fromEntries(values),featured:values.has('featured'),wide:values.has('wide'),published:event.submitter.value==='publish'};operation(async()=>{await api(`/api/admin/media/${body.media_id}`,{method:'PUT',body:json({alt_text:body.alt_text,category:media.find(row=>row.id===body.media_id).category})});const result=await api(itemId==='new'?'/api/admin/gallery':`/api/admin/gallery/${itemId}`,{method:itemId==='new'?'POST':'PUT',body:json(body)});dirty=false;history.replaceState({},'',`/admin/gallery?edit=${result.id||itemId}`);await galleryPage();notice(body.published?'Gallery photo published.':'Gallery photo saved as draft.');});});
}
async function documentPage(name){
  await loadLibrary();const record=await api(`/api/admin/documents/${name}`),data=record.draft;let fields='';
  if(name==='homepage')fields=`<div class="form-grid">${photoSelect('Hero photo','hero_media_id',data.hero_media_id,true)}${photoSelect('Hero artwork (Art 4)','hero_art_media_id',data.hero_art_media_id,true)}${eventSelect('featured_event_id',data.featured_event_id)}<div class="full">${area('Hero introduction','hero_description',data.hero_description,500)}</div></div><p><a class="inline-link" data-route href="/admin/art-forms">Change Music, Dance and Fine Arts images ↗</a></p><p><a class="inline-link" data-route href="/admin/gallery">Choose featured gallery photos ↗</a></p>`;
  if(name==='content')fields=`${area('About VPA','about',data.about,2000)}${area('Vision','vision',data.vision,3000)}${area('Mission (blank lines separate paragraphs)','mission',data.mission,4000)}${field('Instagram profile','instagram',data.instagram,'url','required')}`;
  if(name==='art-forms')fields=data.map((item,index)=>`<fieldset data-form-index="${index}"><legend>${escape(item.category)}</legend><div class="form-grid">${photoSelect('Featured image',`photo_${index}`,item.media_id,true)}${eventSelect(`event_${index}`,item.featured_event_id)}<div class="full">${area('Short description',`description_${index}`,item.description,500)}</div><label class="full">Supporting gallery<select multiple name="gallery_${index}" size="5">${media.map(photo=>`<option value="${photo.id}" ${item.gallery_media_ids.includes(photo.id)?'selected':''}>${escape(photo.filename)}</option>`).join('')}</select><span class="hint">Use Ctrl/Cmd to choose multiple photos.</span></label></div></fieldset>`).join('');
  if(name==='team')fields=data.map((item,index)=>`<fieldset><legend>${escape(item.role)}</legend><div class="form-grid">${field('Name',`name_${index}`,item.name,'text','required')}${field('Role',`role_${index}`,item.role,'text','required')}${photoSelect('Portrait',`photo_${index}`,item.media_id,true)}${field('Display order',`order_${index}`,index+1,'number','min="1" max="30" required')}${check('Crop phone controls from supplied screenshot',`crop_${index}`,item.crop==='portrait-screenshot')}</div></fieldset>`).join('');
  page.innerHTML=heading({'homepage':'The opening act.','content':'The words behind VPA.','art-forms':'Three forms. One stage.','team':'The people behind VPA.'}[name],'Edit the content. The design stays protected.')+`<p class="notice">Save draft keeps the live version unchanged. Preview saved drafts, then publish when ready.</p><form id="document-editor" data-editor><div class="panel">${fields}</div>${editorActions()}</form>`;
  document.querySelector('#document-editor').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,values=new FormData(form),publish=event.submitter.value==='publish';let body;if(name==='homepage'||name==='content')body=Object.fromEntries(values);if(name==='art-forms')body=data.map((item,index)=>({...item,media_id:values.get(`photo_${index}`),description:values.get(`description_${index}`),featured_event_id:values.get(`event_${index}`),gallery_media_ids:values.getAll(`gallery_${index}`)}));if(name==='team')body=data.map((item,index)=>({...item,name:values.get(`name_${index}`),role:values.get(`role_${index}`),media_id:values.get(`photo_${index}`),position:Number(values.get(`order_${index}`)),crop:values.has(`crop_${index}`)?'portrait-screenshot':''})).sort((a,b)=>a.position-b.position);operation(async()=>{const result=await api(`/api/admin/documents/${name}`,{method:'PUT',body:json({data:body,publish})});dirty=false;await documentPage(name);notice(result.message);});});
}
async function render(){previousURL=location.href;document.querySelectorAll('[data-route]').forEach(link=>{if(new URL(link.href).pathname===location.pathname)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');});page.innerHTML='<p>Loading…</p>';try{const section=location.pathname.split('/')[2]||'';if(!section)await dashboard();else if(section==='events')await eventList();else if(section==='media')await mediaPage();else if(section==='gallery')await galleryPage();else await documentPage(section);}catch(error){page.innerHTML='<p>Could not load this page. Please refresh to try again.</p>';notice(error.message,true);}}
refreshSession().then(render).catch(()=>location.replace('/admin/login'));
